import 'package:generic_bloc/entities/car.dart';
import 'package:generic_bloc/entities/person.dart';

const people = [
  Person(name: 'John', age: 25, email: 'john@gmail.com'),
  Person(name: 'Mary', age: 30, email: 'mary@gmail.com'),
  Person(name: 'Peter', age: 35, email: 'peter@gmail.com'),
  Person(name: 'Sarah', age: 40, email: 'sarah@gmail.com'),
  Person(name: 'Mike', age: 45, email: 'mike@gmail.com'),
  Person(name: 'Anna', age: 50, email: 'anna@gmail.com'),
  Person(name: 'David', age: 55, email: 'david@gmail.com'),
  Person(name: 'Steve', age: 60, email: 'steve@gmail.com'),
  Person(name: 'Tom', age: 65, email: 'tom@gmail.com'),
  Person(name: 'Lisa', age: 70, email: 'lisa@gmail.com'),
  Person(name: 'Jane', age: 75, email: 'jane@gmail.com'),
  Person(name: 'Jack', age: 80, email: 'jack@gmail.com'),
  Person(name: 'Jenny', age: 85, email: 'jenny@gmail.com'),
  Person(name: 'Kate', age: 90, email: 'kate@gmail.com'),
  Person(name: 'Linda', age: 95, email: 'linda@gmail.com'),
  Person(name: 'Maria', age: 100, email: 'maria@gmail.com'),
  Person(name: 'Tina', age: 105, email: 'tina@gmail.com'),
  Person(name: 'Lucy', age: 110, email: 'lucy@gmail.com'),
  Person(name: 'Olivia', age: 115, email: 'olivia@gmail.com'),
  Person(name: 'Emily', age: 120, email: 'emily@gmail.com'),
  Person(name: 'Samantha', age: 125, email: 'samantha@gmail.com'),
  Person(name: 'Sophia', age: 130, email: 'sophia@gmail.com'),
  Person(name: 'Mia', age: 135, email: 'mia@gmail.com'),
  Person(name: 'Emma', age: 140, email: 'emma@gmail.com'),
  Person(name: 'Olivia', age: 145, email: 'olivia@gmail.com'),
  Person(name: 'Ava', age: 150, email: 'ava@gmail.com'),
  Person(name: 'Isabella', age: 155, email: 'isabella@gmail.com'),
  Person(name: 'Sophia', age: 160, email: 'sophia@gmail.com'),
  Person(name: 'Mia', age: 165, email: 'mia@gmail.com'),
  Person(name: 'Emma', age: 170, email: 'emma@gmail.com'),
  Person(name: 'Olivia', age: 175, email: 'olivia@gmail.com'),
  Person(name: 'Ava', age: 180, email: 'ava@gmail.com'),
  Person(name: 'Isabella', age: 185, email: 'isabella@gmail.com'),
  Person(name: 'Sophia', age: 190, email: 'sophia@gmail.com'),
  Person(name: 'Mia', age: 195, email: 'mia@gmail.com'),
  Person(name: 'Emma', age: 200, email: 'emma@gmail.com'),
  Person(name: 'Olivia', age: 205, email: 'olivia@gmail.com'),
  Person(name: 'Ava', age: 210, email: 'ava@gmail.com'),
  Person(name: 'Isabella', age: 215, email: 'isabella@gmail.com'),
  Person(name: 'Sophia', age: 220, email: 'sophia@gmail.com'),
  Person(name: 'Mia', age: 225, email: 'mia@gmail.com'),
  Person(name: 'Emma', age: 230, email: 'emma@gmail.com'),
];

const cars = [
  Car(brand: 'Toyota', model: 'Camry', year: 2020),
  Car(brand: 'Honda', model: 'Civic', year: 2020),
  Car(brand: 'Ford', model: 'Mustang', year: 2020),
  Car(brand: 'Chevrolet', model: 'Corvette', year: 2020),
  Car(brand: 'Nissan', model: 'Altima', year: 2020),
  Car(brand: 'Hyundai', model: 'Elantra', year: 2020),
  Car(brand: 'Kia', model: 'Picanto', year: 2020),
  Car(brand: 'Subaru', model: 'Impreza', year: 2020),
  Car(brand: 'Mazda', model: 'MX-5', year: 2020),
  Car(brand: 'Volkswagen', model: 'Passat', year: 2020),
  Car(brand: 'BMW', model: 'M3', year: 2020),
  Car(brand: 'Mercedes-Benz', model: 'S-Class', year: 2020),
  Car(brand: 'Audi', model: 'A8', year: 2020),
  Car(brand: 'Porsche', model: '911', year: 2020),
  Car(brand: 'Volvo', model: 'XC90', year: 2020),
  Car(brand: 'Jaguar', model: 'F-Type', year: 2020),
  Car(brand: 'Aston Martin', model: 'DB9', year: 2020),
  Car(brand: 'Bentley', model: 'Continental GT', year: 2020),
  Car(brand: 'Lexus', model: 'RX', year: 2020),
  Car(brand: 'Bugatti', model: 'Chiron', year: 2020),
  Car(brand: 'Lamborghini', model: 'Murciélago', year: 2020),
  Car(brand: 'Ferrari', model: 'California', year: 2020),
  Car(brand: 'Rolls-Royce', model: 'Ghost', year: 2020),
  Car(brand: 'McLaren', model: '570GT', year: 2020),
  Car(brand: 'Aston Martin', model: 'DBS', year: 2020),
  Car(brand: 'Lotus', model: 'Evora', year: 2020),
  Car(brand: 'Ferrari', model: '488 GTB', year: 2020),
  Car(brand: 'Maserati', model: 'GranTurismo', year: 2020),
  Car(brand: 'Lamborghini', model: 'Aventador', year: 2020),
  Car(brand: 'Porsche', model: '911', year: 2020),
  Car(brand: 'Bugatti', model: 'Chiron', year: 2020),
  Car(brand: 'McLaren', model: '570GT', year: 2020),
  Car(brand: 'Aston Martin', model: 'DBS', year: 2020),
  Car(brand: 'Lotus', model: 'Evora', year: 2020),
  Car(brand: 'Ferrari', model: '488 GTB', year: 2020),
  Car(brand: 'Maserati', model: 'GranTurismo', year: 2020),
];
